apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: yourusername/myapp:latest
        imagePullPolicy: IfNotPresent  # Use local images in Minikube
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "test"
        - name: APP_VERSION
          value: "BUILD_NUMBER_PLACEHOLDER"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: NAMESPACE_PLACEHOLDER
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort  # Better for local Minikube